"""Config upgrade: add keys the current format introduced, preserving operator values.

The ``upgrade-config`` CLI command (``cli.cmd_upgrade_config``) uses this to bring an operator's
``config.yaml`` up to the current format after a package upgrade: any key the packaged template has
but the operator's file lacks is added with the template's default; **every existing operator value
is kept untouched**; ``schema_version`` is stamped to :data:`CONFIG_SCHEMA_VERSION`.

This is the *simple* migration path (spec "Versioning & compatibility"): it operates on parsed YAML
mappings and re-emits via ``yaml.safe_dump``, so inline comments are not preserved — the regenerated
file carries a short header pointing back to ``config.example.yaml`` for documentation.
"""

from __future__ import annotations

from collections.abc import Mapping
from importlib import resources
from typing import Any

import yaml

from wastech_orchestrator.config.schema import CONFIG_SCHEMA_VERSION

# Dotted paths of keys removed by a past schema bump. ``upgrade-config`` strips them from an
# operator's config so the regenerated file matches the current schema. Each entry is (parent-path,
# key); an empty parent-path means a top-level key. (v9: the whole ``prompts`` block is gone — a
# flow node's prompt template is its ``role_file``.)
_REMOVED_KEYS: tuple[tuple[str, str], ...] = (
    ("", "prompts"),
)

_UPGRADE_HEADER = (
    "# Regenerated by `wastech-orchestrator upgrade-config`.\n"
    "# New keys were added from the packaged template with their default values; your existing\n"
    "# values were preserved. Inline comments are not kept here — see config.example.yaml and\n"
    "# docs/configuration.md for documentation of every field.\n"
)


def parse_mapping(text: str) -> dict[str, Any]:
    """Parse config YAML text into a plain mapping (``{}`` for an empty/non-mapping document)."""
    data = yaml.safe_load(text)
    if not isinstance(data, Mapping):
        return {}
    return {str(k): v for k, v in data.items()}


def packaged_template_mapping() -> dict[str, Any]:
    """The packaged ``config.example.yaml`` parsed into a mapping (source of new-key defaults)."""
    text = (
        resources.files("wastech_orchestrator")
        .joinpath("templates", "config.example.yaml")
        .read_text(encoding="utf-8")
    )
    return parse_mapping(text)


def upgrade_config_mapping(
    template: Mapping[str, Any], operator: Mapping[str, Any]
) -> tuple[dict[str, Any], list[str], list[str]]:
    """Merge ``template`` into ``operator``, adding only what is missing and stripping removed keys.

    Returns ``(merged, added, removed)``: ``added`` is the dotted paths of keys taken from the
    template because the operator's config lacked them; ``removed`` is the dotted paths of legacy
    keys (see :data:`_REMOVED_KEYS`) dropped from the operator's config. Operator values win at
    every existing leaf; nested mappings are merged recursively (so a *new sub-key* under an
    existing block is added without touching its siblings); operator-only keys are preserved unless
    removed. ``schema_version`` is always set to :data:`CONFIG_SCHEMA_VERSION`.
    """
    added: list[str] = []
    merged = _merge(template, operator, prefix="", added=added)
    removed = _strip_removed_keys(merged)
    merged["schema_version"] = CONFIG_SCHEMA_VERSION
    return merged, added, removed


def _strip_removed_keys(merged: dict[str, Any]) -> list[str]:
    """Drop :data:`_REMOVED_KEYS` from *merged* in place; return the dotted paths removed."""
    removed: list[str] = []
    for parent, key in _REMOVED_KEYS:
        container: Any = merged
        if parent:
            container = merged.get(parent)
            if not isinstance(container, dict):
                continue
        if key in container:
            del container[key]
            removed.append(f"{parent}.{key}" if parent else key)
    return removed


def _merge(
    template: Mapping[str, Any], operator: Mapping[str, Any], *, prefix: str, added: list[str]
) -> dict[str, Any]:
    result: dict[str, Any] = {}
    # Template-ordered keys first, so newly-added keys land in the documented order.
    for key, tval in template.items():
        path = f"{prefix}{key}"
        if key in operator:
            oval = operator[key]
            if isinstance(tval, Mapping) and isinstance(oval, Mapping):
                result[key] = _merge(tval, oval, prefix=f"{path}.", added=added)
            else:
                result[key] = oval  # operator value wins; never overwritten
        else:
            result[key] = tval
            added.append(path)
    # Preserve anything the operator set that the template does not mention.
    for key, oval in operator.items():
        if key not in template:
            result[key] = oval
    return result


def render(mapping: Mapping[str, Any]) -> str:
    """Serialize an upgraded config mapping to YAML text with the upgrade header (stable order)."""
    body = yaml.safe_dump(
        dict(mapping), sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    return _UPGRADE_HEADER + body
