"""Generate a ``config.yaml`` from the installer's resolved settings.

Builds a plain dict mirroring the packaged ``config.example.yaml`` — only the selected providers,
absolute native paths, exactly one global ``primary`` provider, and the shipped security posture —
then renders it with PyYAML. ``build_and_validate`` round-trips the rendered text back through the
loader and the semantic validator, so the installer can never emit a config that is structurally
broken or contradictory.

That posture is the **advanced mode** (``strict_isolation: false``) as of 2026-08-24, and it is
written out key by key rather than left to a fallback: an operator reading their own file sees the
relaxation, and the dataclass/loader defaults stay fail-closed for a config that omits the key.
No secrets are ever written.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from wastech_orchestrator.config.loader import loads_config
from wastech_orchestrator.config.schema import (
    CONFIG_SCHEMA_VERSION,
    DEFAULT_TOOL_TIMEOUT_SECONDS,
)
from wastech_orchestrator.config.validation import validate_config
from wastech_orchestrator.providers.base import ProviderId
from wastech_orchestrator.runtime_layout import RuntimeLayout
from wastech_orchestrator.security.env import default_allowed_environment

_HEADER = (
    "# Generated by `wastech-orchestrator install`. Safe to edit by hand.\n"
    "# All paths are absolute. The orchestrator's runtime files live under the gitignored\n"
    "# <repo>/.worc/ home (this config included); the task + its summary are committed in the\n"
    "# repo under tasks/. Every field and validation rule is documented in the annotated\n"
    "# config.example.yaml installed alongside this file under .worc/.\n"
)


@dataclass(frozen=True)
class InstallSpec:
    """The settings the wizard resolves and the config generator serializes."""

    repo_url: str
    repo_local_path: Path
    base_branch: str
    providers: tuple[ProviderId, ...]
    create_pull_request: bool
    auto_mode: bool


def _ordered_providers(providers: tuple[ProviderId, ...]) -> tuple[ProviderId, ...]:
    """Canonical, deterministic provider order regardless of how the wizard collected them."""
    selected = set(providers)
    return tuple(pid for pid in ProviderId if pid in selected)


# Shipped default ``(model, reasoning)`` per provider (provider-config-cleanup #3). These replace
# the old empty ``""`` / ``null`` placeholders; ``""`` / blank stays a valid "use the CLI/account
# default" sentinel, so an operator may still clear either field. Keep the Codex id in step with the
# installed Codex CLI's accepted ``--model`` values.
_PROVIDER_DEFAULTS: dict[ProviderId, tuple[str, str]] = {
    ProviderId.CLAUDE: ("claude-sonnet-5", "high"),
    ProviderId.CODEX: ("gpt-5.4", "high"),
}


def _provider_block(pid: ProviderId, *, primary: bool) -> dict[str, Any]:
    """One ``agents.providers.<id>`` block, mirroring the packaged template's safe defaults."""
    model, reasoning = _PROVIDER_DEFAULTS[pid]
    block: dict[str, Any] = {
        "command": pid.value,
        "model": model,
        "reasoning": reasoning,
        "timeout_seconds": 7200,
    }
    if pid is ProviderId.CLAUDE:
        block["max_turns"] = 400
        # Off by default; when on, a run that hits ``max_turns`` pauses for a Telegram continue/stop
        # prompt (requires telegram.enabled) and a low ``max_turns`` (~50–100) becomes safe.
        block["max_turns_gate"] = False
    block["permission_profile"] = "workspace-write"
    block["extra_args"] = []
    if primary:
        block["primary"] = True  # exactly one global primary (PRE.1)
    return block


def _global_primary(providers: tuple[ProviderId, ...]) -> ProviderId:
    """The single global primary: prefer Claude when selected, else the first provider."""
    return ProviderId.CLAUDE if ProviderId.CLAUDE in providers else providers[0]


def build_config_mapping(spec: InstallSpec) -> dict[str, Any]:
    """Assemble the config as a primitive dict (str/int/bool/None only) ready for YAML."""
    providers = _ordered_providers(spec.providers)
    primary_pid = _global_primary(providers)
    # Rejected runtime tasks live under the private home; routed through the layout so no
    # bare ``.worc`` literal is reconstructed here.
    private_home = RuntimeLayout.default(spec.repo_local_path).private_home
    quarantine = str(private_home / "tasks" / "rejected")
    return {
        "schema_version": CONFIG_SCHEMA_VERSION,
        "orchestrator": {
            "auto_mode": {"enabled": spec.auto_mode, "confirm_next_task": False},
            "poll_interval_seconds": 300,
            "queue": "default",
        },
        "repo": {
            "url": spec.repo_url,
            "local_path": str(spec.repo_local_path),
            "base_branch": spec.base_branch,
            "branch_prefix": "worc",
            # Instance default for where task git operations point (a per-task `branch_mode` wins).
            "branch_mode": "new",
        },
        # The default reproduces the historical `tasks/` layout; an operator renames it (and creates
        # the lifecycle subfolders) to avoid clashing with a repo that already uses `tasks/`.
        "paths": {"tasks_dir": "tasks"},
        "agents": {
            "allowed": [pid.value for pid in providers],
            "max_stage_attempts": 3,
            "max_fix_cycles": 15,
            "max_total_fix_iterations": 30,
            "decomposition": {
                "enabled": False,
                "max_subtasks": 8,
            },
            "retry": {
                "max_attempts": 2,
                "base_delay_s": 2.0,
                "max_delay_s": 30.0,
                "max_blocked_s": 21600.0,
            },
            "providers": {
                pid.value: _provider_block(pid, primary=(pid is primary_pid)) for pid in providers
            },
        },
        "security": {
            # Advanced mode out of the box (operator decision of 2026-08-24): full freedom for the
            # agent under the operator's responsibility, except the floor. The dataclass/loader
            # fallback stays `true`, so a config that OMITS this key is still fail-closed — only
            # what `install` writes is the relaxed posture, and it writes it visibly.
            "strict_isolation": False,
            # Written explicitly although it is redundant at `strict_isolation: false` (the
            # effective value is `disable_read_isolation OR NOT strict_isolation`): the operator
            # asked for the read-side posture to be readable in their own file rather than inferred
            # from the master switch, and it is what takes effect if they turn strict back on.
            "disable_read_isolation": True,
            # OS-aware: the cross-platform base plus the OS-launch essentials of the machine the
            # installer runs on (e.g. SystemRoot on Windows, without which the Node-based claude.exe
            # crashes at startup). We write the host OS's set only — the other OS's names are never
            # dragged in. See wastech_orchestrator.security.env.default_allowed_environment.
            "allowed_environment": list(default_allowed_environment()),
            # Seeded empty and seeded *explicitly*, like the switches below: the key that ASSIGNS a
            # variable (toolchain root, cache path) belongs in the operator's own config where they
            # will find it, not as a hidden default they have to read the reference to discover.
            # Empty => the child environment is exactly what forwarding alone produces.
            "extra_environment": {},
            "denied_read_paths": [".env", "secrets/**"],
            "denied_commands": ["git commit", "git push", "gh pr create", "gh pr merge"],
            # Written explicitly at the one default "auto" carries everywhere (dataclass, loader,
            # and here): routine in-repo deletions/renames never gate — only a `protected_paths`
            # match asks.
            "trust_level": "auto",
            "protected_paths": [],
            # Seeded on, and seeded *explicitly*: the read-only git-evidence grant is a decision
            # the operator should find in their own config rather than discover as a hidden
            # default. Inert beside the `strict_isolation: false` above — the advanced mode already
            # hands every node an unscoped shell, so the grant has no capability left to add — and
            # it is what a node declaring `git_evidence` gets the moment strict isolation returns.
            "allow_git_evidence": True,
        },
        "validation": {
            "max_task_bytes": 262144,
            "max_task_lines": 5000,
            "max_line_bytes": 8192,
            "max_control_ratio": 0.01,
            "quarantine_folder": quarantine,
        },
        "checks": {
            # No gate is seeded: the operator authors ``command_sets`` (see config.example.yaml).
            "command_sets": {},
            "timeout_seconds": 7200,
        },
        "git": {
            "create_pull_request": spec.create_pull_request,
            "pr_base": spec.base_branch,
            # Auto-merge bypass — off by default (DANGER: skips review). See config.example.yaml.
            "auto_merge": False,
            "auto_merge_strategy": "squash",
            "auto_merge_wait_for_checks": False,
            # Flow that ``worc merge-task`` runs to resolve base-merge conflicts (clean merges are
            # mechanical). Seeded as an editable copy under .worc/flows/merge.yaml.
            "merge_flow": "merge",
            "footprint": {
                # The task file + its <id>.summary.md are audit-committed in the repo under tasks/;
                # all other runtime artifacts live under the gitignored .worc/ home.
                "audit_commit_message": "chore(worc): audit trail for {task_id}",
                "audit_on_branch": "task",
            },
        },
        "telegram": {
            "enabled": False,
            "bot_token_env": "TELEGRAM_BOT_TOKEN",
            "chat_id_env": "TELEGRAM_CHAT_ID",
            "ask_timeout_s": 28800,
            # Surface the documented per-message HITL trace knob (schema v21) in the delivered
            # config so the operator sees it without reading the source; off by default.
            "trace": False,
        },
        "skills": {
            # Off out of the box — the dynamic layer adds a once-per-task supervisor turn even
            # when the repo has no skills. The operator opts in with `dynamic: true`.
            "dynamic": False,
            "strict": False,
        },
        # Resolve concrete, visible supervisor model/reasoning/provider rather than an implicit
        # "inherit from primary" (null). The oversight layer writes summary / follow-ups /
        # memory-delta, so its model+effort should be transparent. `reasoning` is deliberately NOT a
        # max tier — xhigh makes the structured finalize turn fragile. `provider` is pinned to
        # the primary so it stays aligned with `model` (also the primary's default) by construction
        # so an operator flipping the primary keeps a self-consistent supervisor.
        # Effort is per phase: `observe` is advisory and can fire on every step of a deep fix loop,
        # so it gets the cheap tier; `finalize` writes summary.md (the pull-request body) and
        # `handoff` briefs the next subtask, so both keep the considered `high`. `observe.mode`
        # is written explicitly at the global default — deviations only, so a run pays for
        # observations in proportion to what actually went wrong rather than to its length.
        "supervisor": {
            # Written explicitly at the default so an operator finds the whole-layer switch in their
            # own config rather than in the reference — the same reason `skills.dynamic` and
            # `observe.mode` are seeded rather than left implicit.
            "enabled": True,
            "role_file": "roles/supervisor.md",
            "provider": primary_pid.value,
            "observe": {
                "mode": "events",
                "model": _PROVIDER_DEFAULTS[primary_pid][0],
                "reasoning": "low",
            },
            "finalize": {"model": _PROVIDER_DEFAULTS[primary_pid][0], "reasoning": "high"},
            "handoff": {"model": _PROVIDER_DEFAULTS[primary_pid][0], "reasoning": "high"},
        },
        "logging": {
            "level": "warning",
            "artifacts": "standard",
            "clean_runs_on_success": True,
        },
        # Persistent repo-scoped memory is off out of the box (operator decision of 2026-08-24),
        # which matches the dataclass fallback. Set enabled: true for the store, the candidate
        # delta and the memory packets. The tunable knobs default per the schema — the annotated
        # config.example.yaml installed alongside this file documents each one.
        "memory": {"enabled": False},
        # Custom tool-node default timeout. Written at the schema default for discoverability;
        # a per-node `timeout_seconds` in a flow overrides it. Omit the block for the same 3600s.
        "tools": {"default_timeout_seconds": DEFAULT_TOOL_TIMEOUT_SECONDS},
        "prompt_audit": False,
    }


def render(mapping: dict[str, Any]) -> str:
    """Serialize the config mapping to YAML text (stable key order, paths as literal scalars)."""
    body = yaml.safe_dump(mapping, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return _HEADER + body


def build_and_validate(spec: InstallSpec) -> str:
    """Render the config, then fail-closed verify it loads and passes before returning.

    Raises :class:`~wastech_orchestrator.config.loader.ConfigError` if the generated config is
    structurally invalid or violates a semantic rule — a defensive guard against a generator bug;
    the installer must never persist an unsafe or unloadable config.
    """
    text = render(build_config_mapping(spec))
    validate_config(loads_config(text, source="<generated install config>").config)
    return text
