"""Generate a ``config.yaml`` from the installer's resolved settings.

The generated file is deliberately **small**: it carries only what the install actually resolved
(repo, selected providers, the shipped security posture) plus the handful of knobs an operator
reaches for first. Every other key is left out, because an absent key resolves to the same value
the loader would have written — so the delivered file is what the operator must *decide*, not a
transcript of the schema. The annotated ``config.example.yaml`` installed beside it is the
complete reference; a block moves out of it and into ``config.yaml`` only when the operator wants
to change something.

Two kinds of key survive that rule and are written even though they look ordinary:

* values the install *resolved* — ``repo.*``, ``agents.allowed`` / ``agents.providers.*``,
  ``git.create_pull_request`` / ``pr_base``, ``orchestrator.auto_mode.enabled``;
* values that deviate from the fail-closed dataclass default — the ``security`` posture, which is
  the **advanced mode** (``strict_isolation: false``). It is written key by key so an operator
  reading their own file sees the relaxation, while a config that omits the key stays fail-closed.

``paths.tasks_dir``, ``checks.command_sets`` and ``telegram.enabled`` are the third kind: written
at their default as *affordances* — the operator has to know where tasks live, has to author the
check gate, and should find the HITL switch without reading the reference.

``build_and_validate`` round-trips the rendered text back through the loader and the semantic
validator, so the installer can never emit a config that is structurally broken or contradictory.
No secrets are ever written.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from wastech_orchestrator.config.loader import loads_config
from wastech_orchestrator.config.schema import CONFIG_SCHEMA_VERSION
from wastech_orchestrator.config.validation import validate_config
from wastech_orchestrator.providers.base import ProviderId

_HEADER = (
    "# Generated by `wastech-orchestrator install`. Safe to edit by hand.\n"
    "# Deliberately small: what the install resolved, plus the few knobs you reach for first.\n"
    "# Any key NOT here runs at its documented default — you add one only to change it.\n"
    "# All paths are absolute. The orchestrator's runtime files live under the gitignored\n"
    "# <repo>/.worc/ home (this config included); the task + its summary are committed in the\n"
    "# repo under tasks/. Every field, default and validation rule is documented in the annotated\n"
    "# config.example.yaml installed alongside this file under .worc/.\n"
)

_FOOTER = (
    "\n"
    "# Not written here — each of these runs at its documented default. Copy a block over from\n"
    "# config.example.yaml when you want to change one:\n"
    "#   orchestrator  poll_interval_seconds, queue, auto_mode.confirm_next_task\n"
    "#   repo          branch_prefix, branch_mode, checkout_base_on_cleanup\n"
    "#   agents        the fix budgets, decomposition, retry, and the per-provider command /\n"
    "#                 timeout_seconds / permission_profile / extra_args / max_turns\n"
    "#   security      allowed_environment (resolved per OS at load), extra_environment,\n"
    "#                 denied_read_paths, denied_commands, trust_level, protected_paths\n"
    "#   validation    task-file size limits and the rejected-task quarantine folder\n"
    "#   checks        timeout_seconds\n"
    "#   git           auto_merge*, merge_flow, footprint\n"
    "#   telegram      bot_token_env, chat_id_env, ask_timeout_s, trace\n"
    "#   supervisor    the whole oversight layer — on, and following the primary provider\n"
    "#   logging       level, artifacts, clean_runs_on_success\n"
    "#   tools         default_timeout_seconds\n"
    "#   prompt_audit  off\n"
    "#   memory        EXPERIMENTAL — off, and best left off\n"
)


@dataclass(frozen=True)
class InstallSpec:
    """The settings the wizard resolves and the config generator serializes."""

    repo_url: str
    repo_local_path: Path
    base_branch: str
    providers: tuple[ProviderId, ...]
    create_pull_request: bool
    auto_mode: bool


def _ordered_providers(providers: tuple[ProviderId, ...]) -> tuple[ProviderId, ...]:
    """Canonical, deterministic provider order regardless of how the wizard collected them."""
    selected = set(providers)
    return tuple(pid for pid in ProviderId if pid in selected)


# Shipped default ``(model, reasoning)`` per provider (provider-config-cleanup #3). These replace
# the old empty ``""`` / ``null`` placeholders; ``""`` / blank stays a valid "use the CLI/account
# default" sentinel, so an operator may still clear either field. Keep the Codex id in step with the
# installed Codex CLI's accepted ``--model`` values.
_PROVIDER_DEFAULTS: dict[ProviderId, tuple[str, str]] = {
    ProviderId.CLAUDE: ("claude-sonnet-5", "high"),
    ProviderId.CODEX: ("gpt-5.5", "high"),
}


def _provider_block(pid: ProviderId, *, primary: bool) -> dict[str, Any]:
    """One ``agents.providers.<id>`` block: the model + effort, and the primary marker.

    Everything else a provider accepts (``command``, ``timeout_seconds``, ``permission_profile``,
    ``extra_args``, ``max_turns``, ``max_turns_gate``) is omitted — the loader's fallback for each
    is exactly what this used to write, so spelling them out only added lines to read.
    """
    model, reasoning = _PROVIDER_DEFAULTS[pid]
    block: dict[str, Any] = {"model": model, "reasoning": reasoning}
    if primary:
        block["primary"] = True  # exactly one global primary
    return block


def _global_primary(providers: tuple[ProviderId, ...]) -> ProviderId:
    """The single global primary: prefer Claude when selected, else the first provider."""
    return ProviderId.CLAUDE if ProviderId.CLAUDE in providers else providers[0]


def build_config_mapping(spec: InstallSpec) -> dict[str, Any]:
    """Assemble the config as a primitive dict (str/int/bool/None only) ready for YAML."""
    providers = _ordered_providers(spec.providers)
    primary_pid = _global_primary(providers)
    return {
        "schema_version": CONFIG_SCHEMA_VERSION,
        # The wizard's own answer, so it is written even when it matches the default: the operator
        # should see the mode they chose rather than have to remember what they said.
        "orchestrator": {"auto_mode": {"enabled": spec.auto_mode}},
        "repo": {
            "url": spec.repo_url,
            "local_path": str(spec.repo_local_path),
            "base_branch": spec.base_branch,
        },
        # An affordance, not a knob: written at its default because the operator has to know where
        # task files go, and because a repo that already uses `tasks/` needs to rename it here.
        "paths": {"tasks_dir": "tasks"},
        "agents": {
            "allowed": [pid.value for pid in providers],
            "providers": {
                pid.value: _provider_block(pid, primary=(pid is primary_pid)) for pid in providers
            },
        },
        # The one block whose values deviate from the fail-closed dataclass defaults, so it cannot
        # be omitted the way the rest are: this is the **advanced mode** — full freedom for the
        # agent under the operator's responsibility, except the floor. The loader fallback stays
        # `strict_isolation: true`, so a config that DROPS these keys goes back to fail-closed;
        # only what `install` writes is the relaxed posture, and it writes it visibly.
        "security": {
            "strict_isolation": False,
            # Redundant at `strict_isolation: false` (the effective value is
            # `disable_read_isolation OR NOT strict_isolation`), but kept visible: it is the
            # read-side posture that takes effect the moment strict isolation is turned back on.
            "disable_read_isolation": True,
            # Inert beside the relaxed posture above — the advanced mode already hands every node
            # an unscoped shell — and it is what a node declaring `git_evidence` gets the moment
            # strict isolation returns.
            "allow_git_evidence": True,
        },
        # The one thing the operator MUST author: their own test/lint gate. Seeded empty (and no
        # `timeout_seconds`) so the shape is visible; see config.example.yaml for the entry form.
        "checks": {"command_sets": {}},
        "git": {
            "create_pull_request": spec.create_pull_request,
            "pr_base": spec.base_branch,
        },
        # The HITL channel, advertised in one line: everything needed to turn it on (the two env
        # var names, the ask timeout) defaults correctly, so `enabled: true` is the whole edit.
        "telegram": {"enabled": False},
    }


def render(mapping: dict[str, Any]) -> str:
    """Serialize the config mapping to YAML text (stable key order, paths as literal scalars)."""
    body = yaml.safe_dump(mapping, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return _HEADER + body + _FOOTER


def build_and_validate(spec: InstallSpec) -> str:
    """Render the config, then fail-closed verify it loads and passes before returning.

    Raises :class:`~wastech_orchestrator.config.loader.ConfigError` if the generated config is
    structurally invalid or violates a semantic rule — a defensive guard against a generator bug;
    the installer must never persist an unsafe or unloadable config.
    """
    text = render(build_config_mapping(spec))
    validate_config(loads_config(text, source="<generated install config>").config)
    return text
