"""Generate a ``config.yaml`` from the installer's resolved settings (spec §11).

Builds a plain dict mirroring the packaged ``config.example.yaml`` — only the selected providers,
absolute native paths, routing derived from the provider selection, and **immutable safe security
defaults** — then renders it with PyYAML. ``build_and_validate`` round-trips the rendered text back
through the loader and the semantic validator, so the installer can never emit a config that is
structurally broken, contradictory, or that weakens the sandbox (.agents/rules/security.md).
No secrets are ever written.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from wastech_orchestrator.config.loader import loads_config
from wastech_orchestrator.config.schema import CONFIG_SCHEMA_VERSION
from wastech_orchestrator.config.validation import validate_config
from wastech_orchestrator.providers.base import ProviderId, Stage

# Routing order for the generated file (mirrors the spec §5 table); also the YAML key order.
_ROUTING_ORDER: tuple[Stage, ...] = (
    Stage.REFINEMENT,
    Stage.PLANNING,
    Stage.IMPLEMENTATION,
    Stage.REVIEW,
    Stage.FIXING,
    Stage.SUMMARY,
)

# Default primary/fallback per stage when BOTH providers are selected (spec §5 default table).
_DEFAULT_BOTH: dict[Stage, tuple[ProviderId, ProviderId]] = {
    Stage.REFINEMENT: (ProviderId.CLAUDE, ProviderId.CODEX),
    Stage.PLANNING: (ProviderId.CLAUDE, ProviderId.CODEX),
    Stage.IMPLEMENTATION: (ProviderId.CLAUDE, ProviderId.CODEX),
    Stage.REVIEW: (ProviderId.CODEX, ProviderId.CLAUDE),
    Stage.FIXING: (ProviderId.CLAUDE, ProviderId.CODEX),
    Stage.SUMMARY: (ProviderId.CLAUDE, ProviderId.CODEX),
}

_HEADER = (
    "# Generated by `wastech-orchestrator install`. Safe to edit by hand.\n"
    "# All paths are absolute. Default footprint is in-repo audit: the task + its summary are\n"
    "# committed in the bound repo; config.yaml and the rejected-task quarantine live in this\n"
    "# workspace. See docs/configuration.md for every field and validation rule.\n"
)


@dataclass(frozen=True)
class InstallSpec:
    """The settings the wizard resolves and the config generator serializes."""

    repo_url: str
    repo_local_path: Path
    base_branch: str
    workspace: Path
    providers: tuple[ProviderId, ...]
    checks: tuple[str, ...]
    create_pull_request: bool
    auto_mode: bool
    # ``configured`` when the operator supplied/confirmed explicit checks; ``auto`` when none were
    # found, so discovery resolves them at preflight/runtime (automatic check discovery §9).
    discovery_mode: str = "configured"


def _ordered_providers(providers: tuple[ProviderId, ...]) -> tuple[ProviderId, ...]:
    """Canonical, deterministic provider order regardless of how the wizard collected them."""
    selected = set(providers)
    return tuple(pid for pid in ProviderId if pid in selected)


def _provider_block(pid: ProviderId) -> dict[str, Any]:
    """One ``agents.providers.<id>`` block, mirroring the packaged template's safe defaults."""
    block: dict[str, Any] = {"command": pid.value, "model": "", "timeout_seconds": 7200}
    if pid is ProviderId.CODEX:
        block["sandbox"] = "workspace-write"
    if pid is ProviderId.CLAUDE:
        block["max_turns"] = 50
        block["max_budget_usd"] = None
    block["permission_profile"] = "workspace-write"
    block["extra_args"] = []
    return block


def _routing_block(providers: tuple[ProviderId, ...]) -> dict[str, Any]:
    """Routing per stage: the §5 default table for both providers, else single-provider routes."""
    if len(providers) == 1:
        only = providers[0].value
        return {stage.value: {"primary": only, "fallback": None} for stage in _ROUTING_ORDER}
    routing: dict[str, Any] = {}
    for stage in _ROUTING_ORDER:
        primary, fallback = _DEFAULT_BOTH[stage]
        routing[stage.value] = {"primary": primary.value, "fallback": fallback.value}
    return routing


def build_config_mapping(spec: InstallSpec) -> dict[str, Any]:
    """Assemble the config as a primitive dict (str/int/bool/None only) ready for YAML."""
    providers = _ordered_providers(spec.providers)
    workspace = str(spec.workspace)
    return {
        "schema_version": CONFIG_SCHEMA_VERSION,
        "orchestrator": {"auto_mode": {"enabled": spec.auto_mode}, "poll_interval_seconds": 300},
        "repo": {
            "url": spec.repo_url,
            "local_path": str(spec.repo_local_path),
            "base_branch": spec.base_branch,
            "branch_prefix": "agent",
        },
        "agents": {
            "allowed": [pid.value for pid in providers],
            "max_stage_attempts": 3,
            "max_fix_cycles": 15,
            "max_total_fix_iterations": 30,
            "decomposition": {
                "enabled": False,
                "max_subtasks": 8,
                "min_size_signal": "large",
                "commit_per_subtask": True,
            },
            "routing": _routing_block(providers),
            "providers": {pid.value: _provider_block(pid) for pid in providers},
        },
        "security": {
            "strict_isolation": True,
            "allowed_environment": [
                "PATH",
                "HOME",
                "USERPROFILE",
                "CODEX_HOME",
                "CLAUDE_CONFIG_DIR",
            ],
            "denied_read_paths": [".env", "secrets/**"],
            "denied_commands": ["git commit", "git push", "gh pr create", "gh pr merge"],
        },
        "validation": {
            "max_task_bytes": 262144,
            "max_task_lines": 5000,
            "max_line_bytes": 8192,
            "max_control_ratio": 0.01,
            "required_fields": ["id", "title"],
            "reject_unknown_fields": True,
            "quarantine_folder": str(spec.workspace / "tasks" / "rejected"),
        },
        "checks": {
            "discovery": {"mode": spec.discovery_mode, "refresh": "on_change"},
            "commands": list(spec.checks),
            "timeout_seconds": 7200,
        },
        "git": {
            "create_pull_request": spec.create_pull_request,
            "pr_base": spec.base_branch,
            # Auto-merge bypass — off by default (DANGER: skips review). See config.example.yaml.
            "auto_merge": False,
            "auto_merge_strategy": "squash",
            "auto_merge_allow_per_task": False,
            "auto_merge_wait_for_checks": False,
            "footprint": {
                # Tasks and their result artifacts live in the target repo and are audit-committed
                # there (§21); the control workspace holds only config.yaml and the quarantine.
                "location": "in_repo",
                "tracking": "commit",
                "external_root": workspace,  # unused under in_repo, kept for round-trip clarity
                "audit_commit_message": "chore(orchestrator): audit trail for {task_id}",
                "audit_on_branch": "task",
            },
        },
        "telegram": {
            "enabled": False,
            "bot_token_env": "TELEGRAM_BOT_TOKEN",
            "chat_id_env": "TELEGRAM_CHAT_ID",
            "ask_timeout_s": 28800,
        },
    }


def render(mapping: dict[str, Any]) -> str:
    """Serialize the config mapping to YAML text (stable key order, paths as literal scalars)."""
    body = yaml.safe_dump(mapping, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return _HEADER + body


def build_and_validate(spec: InstallSpec) -> str:
    """Render the config, then fail-closed verify it loads and passes §11/§21.4 before returning.

    Raises :class:`~wastech_orchestrator.config.loader.ConfigError` if the generated config is
    structurally invalid or violates a semantic rule — a defensive guard against a generator bug;
    the installer must never persist an unsafe or unloadable config.
    """
    text = render(build_config_mapping(spec))
    validate_config(loads_config(text, source="<generated install config>").config)
    return text
